import Head from 'next/head';

export default function Home() {
  
  return (
    <div>
      <Head>
        <meta
          name='Atmosphere'
          content='Zendesk App generated by create next app'
        />
      </Head>
    </div>
  );
}
